version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: communication-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: communication
      MYSQL_USER: usr_communication
      MYSQL_PASSWORD: pass_communication
    ports:
      - "3306:3306"