# Generated by Django 3.1 on 2020-08-24 23:01
import uuid

from django.db import migrations, models
import django.db.models.deletion


def create_communication(apps, schema_editor):
    communication_model = apps.get_model('schedules', 'Communication')
    communication_list = [
        'email',
        'sms',
        'push',
        'whatsapp',
    ]

    for communication in communication_list:
        communication_model.objects.get_or_create(description=communication)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('push', 'push'), ('whatsapp', 'whatsapp')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('recipient', models.CharField(max_length=30)),
                ('reservation', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.communication')),
            ],
        ),
        migrations.RunPython(create_communication)
    ]
