# Generated by Django 3.1 on 2020-08-25 02:53

import communication.schedules.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(
                choices=[
                    ('sent', 'sent'),
                    ('scheduled', 'scheduled'),
                    ('cancelled', 'cancelled')
                ],
                default='scheduled',
                max_length=9
            ),
        ),
    ]
